baseURL = 'http://localhost:9767/'
languageCode = 'en-us'
title = 'Explore cutting-edge technology trends and insightful guides at KabirsPlanet, your go-to tech blog for innovative solutions and expert perspectives.'
theme = 'kabirsplanet'
